MareS1_MapScripts::
	.byte 0


Script_Tombstone_Default::
# 10 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Default
# 11 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Jesus::
# 16 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Jesus
# 17 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Player::
# 22 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Player
# 23 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pyramus::
# 28 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pyramus
# 29 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Thisbe::
# 34 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Thisbe
# 35 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Buddha::
# 40 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Buddha
# 41 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mahometus::
# 46 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mahometus
# 47 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Einstein::
# 52 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Einstein
# 53 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Gandhi::
# 58 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Gandhi
# 59 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Napoleon::
# 64 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Napoleon
# 65 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Marx::
# 70 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Marx
# 71 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Caesar::
# 76 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Caesar
# 77 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Virgil::
# 82 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Virgil
# 83 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Shakespeare::
# 88 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Shakespeare
# 89 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_MartinLuther::
# 94 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_MartinLuther
# 95 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Newton::
# 100 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Newton
# 101 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Columbus::
# 106 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Columbus
# 107 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Augustus::
# 112 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Augustus
# 113 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Khan::
# 118 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Khan
# 119 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_WilliamNorman::
# 124 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_WilliamNorman
# 125 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Cleopatra::
# 130 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Cleopatra
# 131 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Richard1::
# 136 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Richard1
# 137 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lincoln::
# 142 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lincoln
# 143 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_AlexanderGreat::
# 148 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_AlexanderGreat
# 149 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_KarlusMagnus::
# 154 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_KarlusMagnus
# 155 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Socrates::
# 160 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Socrates
# 161 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Plato::
# 166 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Plato
# 167 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Aristotle::
# 172 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Aristotle
# 173 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Turing::
# 178 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Turing
# 179 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lovelace::
# 184 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lovelace
# 185 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_JohnLinn::
# 190 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_JohnLinn
# 191 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_JamesStrait::
# 196 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_JamesStrait
# 197 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Jerry::
# 202 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Jerry
# 203 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Phil::
# 208 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Phil
# 209 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ryan::
# 214 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ryan
# 215 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Maggie::
# 220 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Maggie
# 221 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ramiro::
# 226 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ramiro
# 227 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Kira::
# 232 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Kira
# 233 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bo::
# 238 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bo
# 239 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_SawyerHawkins::
# 244 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_SawyerHawkins
# 245 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_MichaelDavis::
# 250 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_MichaelDavis
# 251 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hunter::
# 256 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hunter
# 257 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Owsley::
# 262 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Owsley
# 263 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Brent::
# 268 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Brent
# 269 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pigpen::
# 274 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pigpen
# 275 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Keith::
# 280 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Keith
# 281 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_BillGraham::
# 286 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_BillGraham
# 287 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_CowboyNeal::
# 292 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_CowboyNeal
# 293 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Antony::
# 298 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Antony
# 299 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Wright1::
# 304 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Wright1
# 305 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Wright2::
# 310 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Wright2
# 311 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Jefferson::
# 317 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Jefferson
# 318 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Adams::
# 324 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Adams
# 325 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lennon::
# 330 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lennon
# 331 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Harrison::
# 336 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Harrison
# 337 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Washington::
# 342 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Washington
# 343 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hisler::
# 348 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hisler
# 349 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Elizabeth::
# 354 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Elizabeth
# 355 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Thucydides::
# 360 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Thucydides
# 361 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ford::
# 366 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ford
# 367 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Rockefeller::
# 372 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Rockefeller
# 373 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Morgan::
# 378 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Morgan
# 379 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mays::
# 384 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mays
# 385 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Kubrick::
# 390 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Kubrick
# 391 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Brando::
# 396 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Brando
# 397 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Gutenburg::
# 402 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Gutenburg
# 403 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Horace::
# 408 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Horace
# 409 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_CatoElder::
# 414 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_CatoElder
# 415 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Dickens::
# 420 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Dickens
# 421 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Darwin::
# 426 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Darwin
# 427 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pasteur::
# 432 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pasteur
# 433 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Fleming::
# 438 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Fleming
# 439 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tubman::
# 444 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tubman
# 445 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_VanGogh::
# 450 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_VanGogh
# 451 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Picasso::
# 456 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Picasso
# 457 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_ChienShiungWu::
# 462 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_ChienShiungWu
# 463 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Tombstone_Text_Default::
# 470 "data/maps/MareS1/scripts.pory"
	.string "The inscription is too faded to read.$"

Tombstone_Text_Jesus::
# 474 "data/maps/MareS1/scripts.pory"
	.string "IESVS NAZARENVS\n"
	.string "DCCLVIII - DCCXC$"

Tombstone_Text_Player::
# 478 "data/maps/MareS1/scripts.pory"
	.string "{PLAYER}\n"
	.string "MMDCCL - MMDCCLXXVIII$"

Tombstone_Text_Pyramus::
# 482 "data/maps/MareS1/scripts.pory"
	.string "PYRAMVS$"

Tombstone_Text_Thisbe::
# 486 "data/maps/MareS1/scripts.pory"
	.string "THISBE$"

Tombstone_Text_Buddha::
# 490 "data/maps/MareS1/scripts.pory"
	.string "SIDDHARTHA GVATAMA\n"
	.string "CCLXXIV - CCCLIII$"

Tombstone_Text_Mahometus::
# 494 "data/maps/MareS1/scripts.pory"
	.string "MAHOMETVS MECCAE\n"
	.string "MCCCXXIV - MCCCLXXXV$"

Tombstone_Text_Einstein::
# 498 "data/maps/MareS1/scripts.pory"
	.string "ALBERTVS EINSTEIN\n"
	.string "MMDCXXXII - MMDCCVIII$"

Tombstone_Text_Gandhi::
# 502 "data/maps/MareS1/scripts.pory"
	.string "MOHANDAS GANDHI\n"
	.string "MMDCXXII - MMDCCI$"

Tombstone_Text_Napoleon::
# 506 "data/maps/MareS1/scripts.pory"
	.string "NAPOLIO BONAPARS\n"
	.string "MMDXXII - MMDLXXIV$"

Tombstone_Text_Marx::
# 510 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS MARXIVS\n"
	.string "MMDLXXI - MMDCXXXVI$"

Tombstone_Text_Caesar::
# 514 "data/maps/MareS1/scripts.pory"
	.string "GAIVS IVLIVS CAESAR\n"
	.string "DCLIV - DCCX$"

Tombstone_Text_Virgil::
# 518 "data/maps/MareS1/scripts.pory"
	.string "PVBLIVS VERGILIVS MARO\n"
	.string "DCLXXXIV - DCCXXXV$"

Tombstone_Text_Shakespeare::
# 522 "data/maps/MareS1/scripts.pory"
	.string "GVLIELMVS SHAKESPERIVS\n"
	.string "MMCCCXVII - MMCCCLXIX$"

Tombstone_Text_MartinLuther::
# 526 "data/maps/MareS1/scripts.pory"
	.string "MARTINVS LVTHERVS\n"
	.string "MMCCXXXVI - MMCCXCIX$"

Tombstone_Text_Newton::
# 530 "data/maps/MareS1/scripts.pory"
	.string "ISAACVS NEVTONVS\n"
	.string "MMCCCXCV - MMCDLXXX$"

Tombstone_Text_Columbus::
# 534 "data/maps/MareS1/scripts.pory"
	.string "CHRISTOPHORVS COLVMBVS\n"
	.string "MMCCIV - MMCCLIX$"

Tombstone_Text_Augustus::
# 538 "data/maps/MareS1/scripts.pory"
	.string "GAIVS OCTAVIVS\n"
	.string "DCXCI - DCCLXVII$"

Tombstone_Text_Khan::
# 542 "data/maps/MareS1/scripts.pory"
	.string "BORIGIN TEMUGIN\n"
	.string "MCMXV - MCMLXXX$"

Tombstone_Text_WilliamNorman::
# 546 "data/maps/MareS1/scripts.pory"
	.string "GVLIELMVS NORMANNVS\n"
	.string "MDCCLXXXI - MDCCCXL$"

Tombstone_Text_Cleopatra::
# 550 "data/maps/MareS1/scripts.pory"
	.string "CLEOPATRA PHILOPATOR\n"
	.string "DCLXXXV - DCCXXIV$"

Tombstone_Text_Richard1::
# 554 "data/maps/MareS1/scripts.pory"
	.string "RICARDVS PLANTAGENISTAE\n"
	.string "MCMX - MCMLII$"

Tombstone_Text_Lincoln::
# 558 "data/maps/MareS1/scripts.pory"
	.string "ABRAHAMVS LINCOLN\n"
	.string "MMDLXII - MMDCXVIII$"

Tombstone_Text_AlexanderGreat::
# 562 "data/maps/MareS1/scripts.pory"
	.string "ALEXANDER MACEDONIAE\n"
	.string "CCCXCVIII - CDXXXI$"

Tombstone_Text_KarlusMagnus::
# 566 "data/maps/MareS1/scripts.pory"
	.string "CAROLUS CAROLINGVS\n"
	.string "MCDXCIII - MDLXVII$"

Tombstone_Text_Socrates::
# 570 "data/maps/MareS1/scripts.pory"
	.string "SOCRATES ATHENARVM\n"
	.string "CCLXXXV - CCCLV$"

Tombstone_Text_Plato::
# 574 "data/maps/MareS1/scripts.pory"
	.string "PLATO ATHENARVM\n"
	.string "CCCXXIX - CDVI$"

Tombstone_Text_Aristotle::
# 578 "data/maps/MareS1/scripts.pory"
	.string "ARISTOTELES STAGIRORVM\n"
	.string "CCCLXXXIV - CDXXXII$"

Tombstone_Text_Turing::
# 582 "data/maps/MareS1/scripts.pory"
	.string "ALANVS TVRING\n"
	.string "MMDCLXV - MMDCCVII$"

Tombstone_Text_Lovelace::
# 586 "data/maps/MareS1/scripts.pory"
	.string "ADA LOVELACE\n"
	.string "MMDLXVIII - MMDCV$"

Tombstone_Text_JohnLinn::
# 590 "data/maps/MareS1/scripts.pory"
	.string "IOANNES LINN\n"
	.string "MMDCXCIV - MMDCCLXXVII$"

Tombstone_Text_JamesStrait::
# 594 "data/maps/MareS1/scripts.pory"
	.string "IACOBVS STRAIT\n"
	.string "MMDCLXXXVIII - MMDCCLXXVI$"

Tombstone_Text_Jerry::
# 598 "data/maps/MareS1/scripts.pory"
	.string "HIERONYMVS GARCIA\n"
	.string "MMDCXCV - MMDCCXLVIII$"

Tombstone_Text_Phil::
# 602 "data/maps/MareS1/scripts.pory"
	.string "PHILLIPPVS LESH\n"
	.string "MMDCXCIII - MMDCCLXXVII$"

Tombstone_Text_Ryan::
# 606 "data/maps/MareS1/scripts.pory"
	.string "RYAN CORSA\n"
	.string "MMDCCXLIX$"

Tombstone_Text_Maggie::
# 610 "data/maps/MareS1/scripts.pory"
	.string "MAGDALENA STRAIT\n"
	.string "MMDCCLII - MMDCCLXXVII$"

Tombstone_Text_Ramiro::
# 614 "data/maps/MareS1/scripts.pory"
	.string "RAMIRVS MELECIO\n"
	.string "MMDCCIL - MMDCCLXIX$"

Tombstone_Text_Kira::
# 618 "data/maps/MareS1/scripts.pory"
	.string "KIRA NORTON\n"
	.string "MMDCCIL - MMDCCLXXV$"

Tombstone_Text_Bo::
# 622 "data/maps/MareS1/scripts.pory"
	.string "BO TRIANTOS\n"
	.string "MMDCCXLV - MMDCCLXXI$"

Tombstone_Text_SawyerHawkins::
# 626 "data/maps/MareS1/scripts.pory"
	.string "SAVYER HAVKINS\n"
	.string "MMDCCLVI - MMDCCLXXII$"

Tombstone_Text_MichaelDavis::
# 630 "data/maps/MareS1/scripts.pory"
	.string "MICHAEL DAVIS\n"
	.string "MMDCCL - MMDCCLXXVI$"

Tombstone_Text_Hunter::
# 634 "data/maps/MareS1/scripts.pory"
	.string "ROBERTVS HVNTER\n"
	.string "MMDCXCIV - MMDCCLXXII$"

Tombstone_Text_Owsley::
# 638 "data/maps/MareS1/scripts.pory"
	.string "AVGVSTVS STANLEY III\n"
	.string "MMDCLXXXVIII - MMDCCLXIV$"

Tombstone_Text_Brent::
# 642 "data/maps/MareS1/scripts.pory"
	.string "BRENT MYDLAND\n"
	.string "MMDCCV - MMDCCXLIII$"

Tombstone_Text_Pigpen::
# 646 "data/maps/MareS1/scripts.pory"
	.string "RONALDVS MCKERNAN\n"
	.string "MMDCXCVIII - MMDCCXXVI$"

Tombstone_Text_Keith::
# 650 "data/maps/MareS1/scripts.pory"
	.string "KEITH GODCHAUX\n"
	.string "MMDCCI - MMDCCXXXIII$"

Tombstone_Text_BillGraham::
# 654 "data/maps/MareS1/scripts.pory"
	.string "VLF GRAIONCA\n"
	.string "MMDCLXXXIV - MMDCCXLIV$"

Tombstone_Text_CowboyNeal::
# 658 "data/maps/MareS1/scripts.pory"
	.string "NEAL CASSADY\n"
	.string "MMDCLXXIX - MMDCCXXI$"

Tombstone_Text_Antony::
# 662 "data/maps/MareS1/scripts.pory"
	.string "MARCVS ANTONIVS\n"
	.string "DCLXXI - DCCXXIV$"

Tombstone_Text_Wright1::
# 666 "data/maps/MareS1/scripts.pory"
	.string "VILBVR VRIGHT\n"
	.string "MMDCXX - MMDCLXV$"

Tombstone_Text_Wright2::
# 670 "data/maps/MareS1/scripts.pory"
	.string "AVRIVILLIUVS VRIGHT\n"
	.string "MMDCXXIV - MMDCCI$"

Tombstone_Text_Jefferson::
# 674 "data/maps/MareS1/scripts.pory"
	.string "THOMAS IEFFERSONIVS\n"
	.string "MMCDXCVI - MMDLXXIX$"

Tombstone_Text_Adams::
# 678 "data/maps/MareS1/scripts.pory"
	.string "IOANNES ADAMIVS\n"
	.string "MMCDLXXXVIII - MMDLXXIX$"

Tombstone_Text_Lennon::
# 682 "data/maps/MareS1/scripts.pory"
	.string "IOANNES LENNON\n"
	.string "MMDCXCIII - MMDCCXXXIII$"

Tombstone_Text_Harrison::
# 686 "data/maps/MareS1/scripts.pory"
	.string "GEORGIVS HARRISON\n"
	.string "MMDCXCVI - MMDCCLIV$"

Tombstone_Text_Washington::
# 690 "data/maps/MareS1/scripts.pory"
	.string "GEORGIVS VASINGTONIUVS\n"
	.string "MMCDLXXXV - MMDLII$"

Tombstone_Text_Hisler::
# 694 "data/maps/MareS1/scripts.pory"
	.string "ADOLPHVS HITLER\n"
	.string "MMDCXLII - MMDCXCVIII$"

Tombstone_Text_Elizabeth::
# 698 "data/maps/MareS1/scripts.pory"
	.string "ELIZABETHA TVDOR\n"
	.string "MMCCLXXXVI - MMCCCLVI$"

Tombstone_Text_Thucydides::
# 702 "data/maps/MareS1/scripts.pory"
	.string "THVCYDIDES ATHENARVM\n"
	.string "CCXCIV - CCCLIV$"

Tombstone_Text_Ford::
# 706 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS FORD\n"
	.string "MMDCXVI - MMDCC$"

Tombstone_Text_Rockefeller::
# 710 "data/maps/MareS1/scripts.pory"
	.string "IOANNES ROCKEFELLER\n"
	.string "MMDXCII - MMDCXC$"

Tombstone_Text_Morgan::
# 714 "data/maps/MareS1/scripts.pory"
	.string "IOANNES MORGAN\n"
	.string "MMDXC - MMDCLXVI$"

Tombstone_Text_Mays::
# 718 "data/maps/MareS1/scripts.pory"
	.string "GVLIELMUS MAYS\n"
	.string "MMDCLXXXIV - MMDCCLXXVII$"

Tombstone_Text_Kubrick::
# 722 "data/maps/MareS1/scripts.pory"
	.string "STANLEY KVBRICK\n"
	.string "MMDCLXXXI - MMDCCLII$"

Tombstone_Text_Brando::
# 726 "data/maps/MareS1/scripts.pory"
	.string "MARLON BRANDO\n"
	.string "MMDCLXXVII - MMDCCLVII$"

Tombstone_Text_Gutenburg::
# 730 "data/maps/MareS1/scripts.pory"
	.string "IOANNES GUTENBERGVS\n"
	.string "MMCLIII - MMCCXXI$"

Tombstone_Text_Horace::
# 734 "data/maps/MareS1/scripts.pory"
	.string "QVINTVS HORATIVS FLACCVS\n"
	.string "DCLXXXIX - DCCXLVI$"

Tombstone_Text_CatoElder::
# 738 "data/maps/MareS1/scripts.pory"
	.string "MARCVS PORCIVS CATO\n"
	.string "DXX - DCV$"

Tombstone_Text_Dickens::
# 742 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS DICKENS\n"
	.string "MMDLXV - MMDCXXIII$"

Tombstone_Text_Darwin::
# 746 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS DARWINIVS\n"
	.string "MMDLXII - MMDCXXXV$"

Tombstone_Text_Pasteur::
# 750 "data/maps/MareS1/scripts.pory"
	.string "LVDOVICVS PASTEVR\n"
	.string "MMDLXXV - MMDCXLVIII$"

Tombstone_Text_Fleming::
# 754 "data/maps/MareS1/scripts.pory"
	.string "ALEXANDER FLEMING\n"
	.string "MMDCXXXIV - MMDCCVIII$"

Tombstone_Text_Tubman::
# 758 "data/maps/MareS1/scripts.pory"
	.string "ARAMINTA ROSS\n"
	.string "MMDLXXV - MMDCLXVI$"

Tombstone_Text_VanGogh::
# 762 "data/maps/MareS1/scripts.pory"
	.string "VINCENTIVS VAN GOGH\n"
	.string "MMDCVI - MMDCXLIII$"

Tombstone_Text_Picasso::
# 766 "data/maps/MareS1/scripts.pory"
	.string "PAVLVS PICASSO\n"
	.string "MMDCXXXIV - MMDCCXXVI$"

Tombstone_Text_ChienShiungWu::
# 770 "data/maps/MareS1/scripts.pory"
	.string "CHIEN SHIUNG WU\n"
	.string "MMCLXV - MMDCCL$"
