MareS1_MapScripts::
	.byte 0


Script_Tombstone_Default::
# 10 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Default
# 11 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Jesus::
# 16 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Jesus
# 17 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Player::
# 22 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Player
# 23 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pyramus::
# 28 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pyramus
# 29 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Thisbe::
# 34 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Thisbe
# 35 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Buddha::
# 40 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Buddha
# 41 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mahometus::
# 46 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mahometus
# 47 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Einstein::
# 52 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Einstein
# 53 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Gandhi::
# 58 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Gandhi
# 59 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Napoleon::
# 64 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Napoleon
# 65 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Marx::
# 70 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Marx
# 71 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Caesar::
# 76 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Caesar
# 77 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Virgil::
# 82 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Virgil
# 83 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Shakespeare::
# 88 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Shakespeare
# 89 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_MartinLuther::
# 94 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_MartinLuther
# 95 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Newton::
# 100 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Newton
# 101 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Columbus::
# 106 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Columbus
# 107 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Augustus::
# 112 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Augustus
# 113 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Khan::
# 118 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Khan
# 119 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_WilliamNorman::
# 124 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_WilliamNorman
# 125 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Cleopatra::
# 130 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Cleopatra
# 131 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Richard1::
# 136 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Richard1
# 137 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lincoln::
# 142 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lincoln
# 143 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_AlexanderGreat::
# 148 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_AlexanderGreat
# 149 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_KarlusMagnus::
# 154 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_KarlusMagnus
# 155 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Socrates::
# 160 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Socrates
# 161 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Plato::
# 166 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Plato
# 167 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Aristotle::
# 172 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Aristotle
# 173 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Turing::
# 178 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Turing
# 179 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lovelace::
# 184 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lovelace
# 185 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_JohnLinn::
# 190 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_JohnLinn
# 191 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_JamesStrait::
# 196 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_JamesStrait
# 197 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Jerry::
# 202 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Jerry
# 203 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Phil::
# 208 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Phil
# 209 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ryan::
# 214 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ryan
# 215 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Maggie::
# 220 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Maggie
# 221 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ramiro::
# 226 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ramiro
# 227 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Kira::
# 232 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Kira
# 233 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bo::
# 238 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bo
# 239 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_SawyerHawkins::
# 244 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_SawyerHawkins
# 245 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_MichaelDavis::
# 250 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_MichaelDavis
# 251 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hunter::
# 256 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hunter
# 257 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Owsley::
# 262 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Owsley
# 263 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Brent::
# 268 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Brent
# 269 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pigpen::
# 274 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pigpen
# 275 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Keith::
# 280 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Keith
# 281 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_BillGraham::
# 286 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_BillGraham
# 287 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_CowboyNeal::
# 292 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_CowboyNeal
# 293 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Antony::
# 298 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Antony
# 299 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Wright1::
# 304 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Wright1
# 305 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Wright2::
# 310 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Wright2
# 311 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Jefferson::
# 317 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Jefferson
# 318 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Adams::
# 324 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Adams
# 325 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lennon::
# 330 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lennon
# 331 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Harrison::
# 336 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Harrison
# 337 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Washington::
# 342 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Washington
# 343 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hisler::
# 348 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hisler
# 349 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Elizabeth::
# 354 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Elizabeth
# 355 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Thucydides::
# 360 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Thucydides
# 361 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ford::
# 366 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ford
# 367 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Rockefeller::
# 372 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Rockefeller
# 373 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Morgan::
# 378 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Morgan
# 379 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mays::
# 384 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mays
# 385 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Kubrick::
# 390 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Kubrick
# 391 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Brando::
# 396 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Brando
# 397 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Gutenburg::
# 402 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Gutenburg
# 403 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Horace::
# 408 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Horace
# 409 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_CatoElder::
# 414 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_CatoElder
# 415 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Dickens::
# 420 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Dickens
# 421 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Darwin::
# 426 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Darwin
# 427 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pasteur::
# 432 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pasteur
# 433 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Fleming::
# 438 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Fleming
# 439 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tubman::
# 444 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tubman
# 445 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_VanGogh::
# 450 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_VanGogh
# 451 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Picasso::
# 456 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Picasso
# 457 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_ChienShiungWu::
# 462 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_ChienShiungWu
# 463 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Faraday::
# 468 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Faraday
# 469 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Maxwell::
# 474 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Maxwell
# 475 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Goethe::
# 480 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Goethe
# 481 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Voltaire::
# 486 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Voltaire
# 487 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Trotsky::
# 492 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Trotsky
# 493 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Kafka::
# 498 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Kafka
# 499 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tolstoy::
# 504 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tolstoy
# 505 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pope::
# 510 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pope
# 511 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_HunterThompson::
# 516 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_HunterThompson
# 517 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Kesey::
# 522 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Kesey
# 523 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_MilesDavis::
# 528 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_MilesDavis
# 529 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Coltrane::
# 534 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Coltrane
# 535 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Dante::
# 540 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Dante
# 541 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Chaucer::
# 546 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Chaucer
# 547 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tchaikovsky::
# 552 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tchaikovsky
# 553 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Montesquieu::
# 558 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Montesquieu
# 559 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Rousseau::
# 564 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Rousseau
# 565 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Paine::
# 570 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Paine
# 571 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Elvis::
# 576 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Elvis
# 577 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ovid::
# 582 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ovid
# 583 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tacitus::
# 588 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tacitus
# 589 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_CatoMinor::
# 594 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_CatoMinor
# 595 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bohr::
# 600 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bohr
# 601 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Descartes::
# 606 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Descartes
# 607 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Aristophanes::
# 612 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Aristophanes
# 613 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hemingway::
# 618 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hemingway
# 619 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ginsberg::
# 624 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ginsberg
# 625 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_VonNeumann::
# 630 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_VonNeumann
# 631 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Edison::
# 636 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Edison
# 637 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Vanderbilt::
# 642 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Vanderbilt
# 643 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Leonidas::
# 648 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Leonidas
# 649 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pompey::
# 654 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pompey
# 655 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pericles::
# 660 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pericles
# 661 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Antigonos::
# 666 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Antigonos
# 667 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Darius::
# 672 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Darius
# 673 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Spartacus::
# 678 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Otto
# 679 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Otto::
# 684 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Otto
# 685 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Justinian::
# 690 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Justinian
# 691 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pepin::
# 696 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pepin
# 697 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Timur::
# 702 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Timur
# 703 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Churchill::
# 708 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Churchill
# 709 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Henry6::
# 714 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Henry6
# 715 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hindenburg::
# 720 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hindenburg
# 721 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Elizabeth2::
# 726 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Elizabeth2
# 727 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Cromwell::
# 732 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Cromwell
# 733 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mao::
# 738 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mao
# 739 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Eisenhower::
# 744 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Eisenhower
# 745 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Ashoka::
# 750 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Ashoka
# 751 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_QinShiHuang::
# 756 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_QinShiHuang
# 757 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Che::
# 762 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Che
# 763 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Cincinnatus::
# 768 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Cincinnatus
# 769 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_MarcusAurelius::
# 774 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_MarcusAurelius
# 775 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Trajan::
# 780 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Trajan
# 781 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Urban2::
# 786 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Urban2
# 787 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Henry8::
# 792 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Henry8
# 793 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_GustavusAdolphus::
# 798 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_GustavusAdolphus
# 799 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Robespierre::
# 804 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Robespierre
# 805 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Lenin::
# 810 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Lenin
# 811 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mandela::
# 816 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mandela
# 817 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Catherine::
# 822 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Catherine
# 823 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bolivar::
# 828 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bolivar
# 829 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bismark::
# 834 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bismark
# 835 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Castro::
# 840 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Castro
# 841 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_FrederickGreat::
# 846 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_FrederickGreat
# 847 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Victoria::
# 852 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Victoria
# 853 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Louis16::
# 858 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Louis16
# 859 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Patton::
# 864 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Patton
# 865 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Louis14::
# 870 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Louis14
# 871 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Atilla::
# 876 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Atilla
# 877 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Sulla::
# 882 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Sulla
# 883 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Xerxes::
# 888 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Xerxes
# 889 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Nero::
# 894 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Nero
# 895 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_EdwardPrince::
# 900 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_EdwardPrince
# 901 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Mussolini::
# 906 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Mussolini
# 907 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Gorbachev::
# 912 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Gorbachev
# 913 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_SusanAnthony::
# 918 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_SusanAnthony
# 919 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Henry4::
# 924 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Henry4
# 925 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Franklin::
# 930 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Franklin
# 931 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tiberius::
# 936 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tiberius
# 937 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_DaVinci::
# 942 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_DaVinci
# 943 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Pythagoras::
# 948 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Pythagoras
# 949 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Feynman::
# 954 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Feynman
# 955 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Sartre::
# 960 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Sartre
# 961 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Nietzshe::
# 966 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Nietzshe
# 967 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Joyce::
# 972 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Joyce
# 973 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bradly::
# 978 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bradly
# 979 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Constantine::
# 984 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Constantine
# 985 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Henry2::
# 990 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Henry2
# 991 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Henry5::
# 996 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Henry5
# 997 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_FrederickBarbarossa::
# 1002 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_FrederickBarbaorossa
# 1003 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_AndrewJackson::
# 1008 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_AndrewJackson
# 1009 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_FDR::
# 1014 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_FDR
# 1015 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Reagan::
# 1020 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Reagan
# 1021 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hirohito::
# 1026 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hirohito
# 1027 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Aquinas::
# 1032 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Aquinas
# 1033 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tesla::
# 1038 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tesla
# 1039 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Bach::
# 1044 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Bach
# 1045 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hobbes::
# 1050 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hobbes
# 1051 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Hendrix::
# 1056 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Hendrix
# 1057 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Tolkien::
# 1062 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Tolkien
# 1063 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Berry::
# 1068 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Berry
# 1069 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Milton::
# 1074 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Milton
# 1075 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Sophocles::
# 1080 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Sophocles
# 1081 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Script_Tombstone_Aeschylus::
# 1086 "data/maps/MareS1/scripts.pory"
	msgbox Tombstone_Text_Aeschylus
# 1087 "data/maps/MareS1/scripts.pory"
	closemessage
	end


Tombstone_Text_Default::
# 1092 "data/maps/MareS1/scripts.pory"
	.string "The inscription is too faded to read.$"

Tombstone_Text_Jesus::
# 1096 "data/maps/MareS1/scripts.pory"
	.string "IESVS NAZARENVS\n"
	.string "DCCLVIII - DCCXC$"

Tombstone_Text_Player::
# 1100 "data/maps/MareS1/scripts.pory"
	.string "{PLAYER}\n"
	.string "MMDCCL - MMDCCLXXVIII$"

Tombstone_Text_Pyramus::
# 1104 "data/maps/MareS1/scripts.pory"
	.string "PYRAMVS$"

Tombstone_Text_Thisbe::
# 1108 "data/maps/MareS1/scripts.pory"
	.string "THISBE$"

Tombstone_Text_Buddha::
# 1112 "data/maps/MareS1/scripts.pory"
	.string "SIDDHARTHA GVATAMA\n"
	.string "CCLXXIV - CCCLIII$"

Tombstone_Text_Mahometus::
# 1116 "data/maps/MareS1/scripts.pory"
	.string "MAHOMETVS MECCAE\n"
	.string "MCCCXXIV - MCCCLXXXV$"

Tombstone_Text_Einstein::
# 1120 "data/maps/MareS1/scripts.pory"
	.string "ALBERTVS EINSTEIN\n"
	.string "MMDCXXXII - MMDCCVIII$"

Tombstone_Text_Gandhi::
# 1124 "data/maps/MareS1/scripts.pory"
	.string "MOHANDAS GANDHI\n"
	.string "MMDCXXII - MMDCCI$"

Tombstone_Text_Napoleon::
# 1128 "data/maps/MareS1/scripts.pory"
	.string "NAPOLIO BONAPARS\n"
	.string "MMDXXII - MMDLXXIV$"

Tombstone_Text_Marx::
# 1132 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS MARXIVS\n"
	.string "MMDLXXI - MMDCXXXVI$"

Tombstone_Text_Caesar::
# 1136 "data/maps/MareS1/scripts.pory"
	.string "GAIVS IVLIVS CAESAR\n"
	.string "DCLIV - DCCX$"

Tombstone_Text_Virgil::
# 1140 "data/maps/MareS1/scripts.pory"
	.string "PVBLIVS VERGILIVS MARO\n"
	.string "DCLXXXIV - DCCXXXV$"

Tombstone_Text_Shakespeare::
# 1144 "data/maps/MareS1/scripts.pory"
	.string "GVLIELMVS SHAKESPERIVS\n"
	.string "MMCCCXVII - MMCCCLXIX$"

Tombstone_Text_MartinLuther::
# 1148 "data/maps/MareS1/scripts.pory"
	.string "MARTINVS LVTHERVS\n"
	.string "MMCCXXXVI - MMCCXCIX$"

Tombstone_Text_Newton::
# 1152 "data/maps/MareS1/scripts.pory"
	.string "ISAACVS NEVTONVS\n"
	.string "MMCCCXCV - MMCDLXXX$"

Tombstone_Text_Columbus::
# 1156 "data/maps/MareS1/scripts.pory"
	.string "CHRISTOPHORVS COLVMBVS\n"
	.string "MMCCIV - MMCCLIX$"

Tombstone_Text_Augustus::
# 1160 "data/maps/MareS1/scripts.pory"
	.string "GAIVS OCTAVIVS\n"
	.string "DCXCI - DCCLXVII$"

Tombstone_Text_Khan::
# 1164 "data/maps/MareS1/scripts.pory"
	.string "BORIGIN TEMVGIN\n"
	.string "MCMXV - MCMLXXX$"

Tombstone_Text_WilliamNorman::
# 1168 "data/maps/MareS1/scripts.pory"
	.string "GVLIELMVS NORMANNVS\n"
	.string "MDCCLXXXI - MDCCCXL$"

Tombstone_Text_Cleopatra::
# 1172 "data/maps/MareS1/scripts.pory"
	.string "CLEOPATRA PHILOPATOR\n"
	.string "DCLXXXV - DCCXXIV$"

Tombstone_Text_Richard1::
# 1176 "data/maps/MareS1/scripts.pory"
	.string "RICARDVS PLANTAGENISTAE\n"
	.string "MCMX - MCMLII$"

Tombstone_Text_Lincoln::
# 1180 "data/maps/MareS1/scripts.pory"
	.string "ABRAHAMVS LINCOLN\n"
	.string "MMDLXII - MMDCXVIII$"

Tombstone_Text_AlexanderGreat::
# 1184 "data/maps/MareS1/scripts.pory"
	.string "ALEXANDER MACEDONIAE\n"
	.string "CCCXCVIII - CDXXXI$"

Tombstone_Text_KarlusMagnus::
# 1188 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS CAROLINGVS\n"
	.string "MCDXCIII - MDLXVII$"

Tombstone_Text_Socrates::
# 1192 "data/maps/MareS1/scripts.pory"
	.string "SOCRATES ATHENARVM\n"
	.string "CCLXXXV - CCCLV$"

Tombstone_Text_Plato::
# 1196 "data/maps/MareS1/scripts.pory"
	.string "PLATO ATHENARVM\n"
	.string "CCCXXIX - CDVI$"

Tombstone_Text_Aristotle::
# 1200 "data/maps/MareS1/scripts.pory"
	.string "ARISTOTELES STAGIRORVM\n"
	.string "CCCLXXXIV - CDXXXII$"

Tombstone_Text_Turing::
# 1204 "data/maps/MareS1/scripts.pory"
	.string "ALANVS TVRING\n"
	.string "MMDCLXV - MMDCCVII$"

Tombstone_Text_Lovelace::
# 1208 "data/maps/MareS1/scripts.pory"
	.string "ADA LOVELACE\n"
	.string "MMDLXVIII - MMDCV$"

Tombstone_Text_JohnLinn::
# 1212 "data/maps/MareS1/scripts.pory"
	.string "IOANNES LINN\n"
	.string "MMDCXCIV - MMDCCLXXVII$"

Tombstone_Text_JamesStrait::
# 1216 "data/maps/MareS1/scripts.pory"
	.string "IACOBVS STRAIT\n"
	.string "MMDCLXXXVIII - MMDCCLXXVI$"

Tombstone_Text_Jerry::
# 1220 "data/maps/MareS1/scripts.pory"
	.string "HIERONYMVS GARCIA\n"
	.string "MMDCXCV - MMDCCXLVIII$"

Tombstone_Text_Phil::
# 1224 "data/maps/MareS1/scripts.pory"
	.string "PHILLIPPVS LESH\n"
	.string "MMDCXCIII - MMDCCLXXVII$"

Tombstone_Text_Ryan::
# 1228 "data/maps/MareS1/scripts.pory"
	.string "RYAN CORSA\n"
	.string "MMDCCXLIX$"

Tombstone_Text_Maggie::
# 1232 "data/maps/MareS1/scripts.pory"
	.string "MAGDALENA STRAIT\n"
	.string "MMDCCLII - MMDCCLXXVII$"

Tombstone_Text_Ramiro::
# 1236 "data/maps/MareS1/scripts.pory"
	.string "RAMIRVS MELECIO\n"
	.string "MMDCCIL - MMDCCLXIX$"

Tombstone_Text_Kira::
# 1240 "data/maps/MareS1/scripts.pory"
	.string "KIRA NORTON\n"
	.string "MMDCCIL - MMDCCLXXV$"

Tombstone_Text_Bo::
# 1244 "data/maps/MareS1/scripts.pory"
	.string "BO TRIANTOS\n"
	.string "MMDCCXLV - MMDCCLXXI$"

Tombstone_Text_SawyerHawkins::
# 1248 "data/maps/MareS1/scripts.pory"
	.string "SAVYER HAVKINS\n"
	.string "MMDCCLVI - MMDCCLXXII$"

Tombstone_Text_MichaelDavis::
# 1252 "data/maps/MareS1/scripts.pory"
	.string "MICHAEL DAVIS\n"
	.string "MMDCCL - MMDCCLXXVI$"

Tombstone_Text_Hunter::
# 1256 "data/maps/MareS1/scripts.pory"
	.string "ROBERTVS HVNTER\n"
	.string "MMDCXCIV - MMDCCLXXII$"

Tombstone_Text_Owsley::
# 1260 "data/maps/MareS1/scripts.pory"
	.string "AVGVSTVS STANLEY III\n"
	.string "MMDCLXXXVIII - MMDCCLXIV$"

Tombstone_Text_Brent::
# 1264 "data/maps/MareS1/scripts.pory"
	.string "BRENT MYDLAND\n"
	.string "MMDCCV - MMDCCXLIII$"

Tombstone_Text_Pigpen::
# 1268 "data/maps/MareS1/scripts.pory"
	.string "RONALDVS MCKERNAN\n"
	.string "MMDCXCVIII - MMDCCXXVI$"

Tombstone_Text_Keith::
# 1272 "data/maps/MareS1/scripts.pory"
	.string "KEITH GODCHAVX\n"
	.string "MMDCCI - MMDCCXXXIII$"

Tombstone_Text_BillGraham::
# 1276 "data/maps/MareS1/scripts.pory"
	.string "VLF GRAIONCA\n"
	.string "MMDCLXXXIV - MMDCCXLIV$"

Tombstone_Text_CowboyNeal::
# 1280 "data/maps/MareS1/scripts.pory"
	.string "NEAL CASSADY\n"
	.string "MMDCLXXIX - MMDCCXXI$"

Tombstone_Text_Antony::
# 1284 "data/maps/MareS1/scripts.pory"
	.string "MARCVS ANTONIVS\n"
	.string "DCLXXI - DCCXXIV$"

Tombstone_Text_Wright1::
# 1288 "data/maps/MareS1/scripts.pory"
	.string "VILBVR VRIGHT\n"
	.string "MMDCXX - MMDCLXV$"

Tombstone_Text_Wright2::
# 1292 "data/maps/MareS1/scripts.pory"
	.string "AVRIVILLIVVS VRIGHT\n"
	.string "MMDCXXIV - MMDCCI$"

Tombstone_Text_Jefferson::
# 1296 "data/maps/MareS1/scripts.pory"
	.string "THOMAS IEFFERSONIVS\n"
	.string "MMCDXCVI - MMDLXXIX$"

Tombstone_Text_Adams::
# 1300 "data/maps/MareS1/scripts.pory"
	.string "IOANNES ADAMIVS\n"
	.string "MMCDLXXXVIII - MMDLXXIX$"

Tombstone_Text_Lennon::
# 1304 "data/maps/MareS1/scripts.pory"
	.string "IOANNES LENNON\n"
	.string "MMDCXCIII - MMDCCXXXIII$"

Tombstone_Text_Harrison::
# 1308 "data/maps/MareS1/scripts.pory"
	.string "GEORGIVS HARRISON\n"
	.string "MMDCXCVI - MMDCCLIV$"

Tombstone_Text_Washington::
# 1312 "data/maps/MareS1/scripts.pory"
	.string "GEORGIVS VASINGTONIVVS\n"
	.string "MMCDLXXXV - MMDLII$"

Tombstone_Text_Hisler::
# 1316 "data/maps/MareS1/scripts.pory"
	.string "ADOLPHVS HITLER\n"
	.string "MMDCXLII - MMDCXCVIII$"

Tombstone_Text_Elizabeth::
# 1320 "data/maps/MareS1/scripts.pory"
	.string "ELIZABETHA TVDOR\n"
	.string "MMCCLXXXVI - MMCCCLVI$"

Tombstone_Text_Thucydides::
# 1324 "data/maps/MareS1/scripts.pory"
	.string "THVCYDIDES ATHENARVM\n"
	.string "CCXCIV - CCCLIV$"

Tombstone_Text_Ford::
# 1328 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS FORD\n"
	.string "MMDCXVI - MMDCC$"

Tombstone_Text_Rockefeller::
# 1332 "data/maps/MareS1/scripts.pory"
	.string "IOANNES ROCKEFELLER\n"
	.string "MMDXCII - MMDCXC$"

Tombstone_Text_Morgan::
# 1336 "data/maps/MareS1/scripts.pory"
	.string "IOANNES MORGAN\n"
	.string "MMDXC - MMDCLXVI$"

Tombstone_Text_Mays::
# 1340 "data/maps/MareS1/scripts.pory"
	.string "GVLIELMVS MAYS\n"
	.string "MMDCLXXXIV - MMDCCLXXVII$"

Tombstone_Text_Kubrick::
# 1344 "data/maps/MareS1/scripts.pory"
	.string "STANLEY KVBRICK\n"
	.string "MMDCLXXXI - MMDCCLII$"

Tombstone_Text_Brando::
# 1348 "data/maps/MareS1/scripts.pory"
	.string "MARLON BRANDO\n"
	.string "MMDCLXXVII - MMDCCLVII$"

Tombstone_Text_Gutenburg::
# 1352 "data/maps/MareS1/scripts.pory"
	.string "IOANNES GVTENBERGVS\n"
	.string "MMCLIII - MMCCXXI$"

Tombstone_Text_Horace::
# 1356 "data/maps/MareS1/scripts.pory"
	.string "QVINTVS HORATIVS FLACCVS\n"
	.string "DCLXXXIX - DCCXLVI$"

Tombstone_Text_CatoElder::
# 1360 "data/maps/MareS1/scripts.pory"
	.string "MARCVS PORCIVS CATO\n"
	.string "DXX - DCV$"

Tombstone_Text_Dickens::
# 1364 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS DICKENS\n"
	.string "MMDLXV - MMDCXXIII$"

Tombstone_Text_Darwin::
# 1368 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS DARWINIVS\n"
	.string "MMDLXII - MMDCXXXV$"

Tombstone_Text_Pasteur::
# 1372 "data/maps/MareS1/scripts.pory"
	.string "LVDOVICVS PASTEVR\n"
	.string "MMDLXXV - MMDCXLVIII$"

Tombstone_Text_Fleming::
# 1376 "data/maps/MareS1/scripts.pory"
	.string "ALEXANDER FLEMING\n"
	.string "MMDCXXXIV - MMDCCVIII$"

Tombstone_Text_Tubman::
# 1380 "data/maps/MareS1/scripts.pory"
	.string "ARAMINTA ROSS\n"
	.string "MMDLXXV - MMDCLXVI$"

Tombstone_Text_VanGogh::
# 1384 "data/maps/MareS1/scripts.pory"
	.string "VINCENTIVS VAN GOGH\n"
	.string "MMDCVI - MMDCXLIII$"

Tombstone_Text_Picasso::
# 1388 "data/maps/MareS1/scripts.pory"
	.string "PAVLVS PICASSO\n"
	.string "MMDCXXXIV - MMDCCXXVI$"

Tombstone_Text_ChienShiungWu::
# 1392 "data/maps/MareS1/scripts.pory"
	.string "CHIEN SHIVNG VV\n"
	.string "MMCLXV - MMDCCL$"

Tombstone_Text_Faraday::
# 1396 "data/maps/MareS1/scripts.pory"
	.string "MICHAEL FARADAY\n"
	.string "MMDCXXXIV - MMDCCXXVI$"

Tombstone_Text_Maxwell::
# 1400 "data/maps/MareS1/scripts.pory"
	.string "IACOBVS MAXVELL\n"
	.string "MMDLXXXIV - MMDCXXXII$"

Tombstone_Text_Goethe::
# 1404 "data/maps/MareS1/scripts.pory"
	.string "iIOANNES GOETHIVS\n"
	.string "MMDII - MMDLXXXV$"

Tombstone_Text_Voltaire::
# 1408 "data/maps/MareS1/scripts.pory"
	.string "FRANCISCVS AROVET\n"
	.string "MMCDXLVII - MMDXXXI$"

Tombstone_Text_Trotsky::
# 1412 "data/maps/MareS1/scripts.pory"
	.string "LEO BRONSTEINVS\n"
	.string "MMDCXXXII - MMDCXCIII$"

Tombstone_Text_Kafka::
# 1416 "data/maps/MareS1/scripts.pory"
	.string "FRANCISCVS KAFKA\n"
	.string "MMDCXXXVI - MMDCLXXVII$"

Tombstone_Text_Tolstoy::
# 1420 "data/maps/MareS1/scripts.pory"
	.string "LEO TOLSTOI\n"
	.string "MMDLXXXI - MMDCLXIII$"

Tombstone_Text_Pope::
# 1424 "data/maps/MareS1/scripts.pory"
	.string "ALEXANDER POPE\n"
	.string "MMCDXLI - MMCDXCVII$"

Tombstone_Text_HunterThompson::
# 1428 "data/maps/MareS1/scripts.pory"
	.string "HVNTER THOMPSON\n"
	.string "MMCXC - MMCCLVIII$"

Tombstone_Text_Kesey::
# 1432 "data/maps/MareS1/scripts.pory"
	.string "KENNETHVS KESEY\n"
	.string "MMDCLXXXVIII - MMDCCLIV$"

Tombstone_Text_MilesDavis::
# 1436 "data/maps/MareS1/scripts.pory"
	.string "MILES DAVIS\n"
	.string "MMCLXXIX - MMDCCXLIV$"

Tombstone_Text_Coltrane::
# 1440 "data/maps/MareS1/scripts.pory"
	.string "IOANNES COLTRANE\n"
	.string "MMCLXXIX - MMDCCXX$"

Tombstone_Text_Dante::
# 1444 "data/maps/MareS1/scripts.pory"
	.string "DANTES ALAGHERIVS\n"
	.string "MMXVIII - MMLXXIV$"

Tombstone_Text_Chaucer::
# 1448 "data/maps/MareS1/scripts.pory"
	.string "GALFRIDVS CHAVCER\n"
	.string "MMXCVI - MMCLIII$"

Tombstone_Text_Tchaikovsky::
# 1452 "data/maps/MareS1/scripts.pory"
	.string "PETRVS CAIKOVSKII\n"
	.string "MMDXCIII - MMDCXLVI$"

Tombstone_Text_Montesquieu::
# 1456 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS MONTESQVIVS\n"
	.string "MMCDXLII - MMDVIII$"

Tombstone_Text_Rousseau::
# 1460 "data/maps/MareS1/scripts.pory"
	.string "IOANNES RVSSAVIVS\n"
	.string "MMCDLXV - MMDXXXI$"

Tombstone_Text_Paine::
# 1464 "data/maps/MareS1/scripts.pory"
	.string "THOMAS PAINE\n"
	.string "MMCDXC - MMDLXII$"

Tombstone_Text_Elvis::
# 1468 "data/maps/MareS1/scripts.pory"
	.string "ELVIS PRESLEY\n"
	.string "MMDCLXXXVIII - MMDCCXXX$"

Tombstone_Text_Ovid::
# 1472 "data/maps/MareS1/scripts.pory"
	.string "PVBLIVS OVIDIVS NASO\n"
	.string "DCCXI - DCCLXX$"

Tombstone_Text_Tacitus::
# 1476 "data/maps/MareS1/scripts.pory"
	.string "CORNELIVS TACITVS\n"
	.string "DCCCIX - DCCCLXXIII$"

Tombstone_Text_CatoMinor::
# 1480 "data/maps/MareS1/scripts.pory"
	.string "MARCVS PORCIVS CATO VTICENSIS\n"
	.string "DCLIX - DCCVIII$"

Tombstone_Text_Bohr::
# 1484 "data/maps/MareS1/scripts.pory"
	.string "NICOLAVS BOHR\n"
	.string "MMDCXXXVIII - MMDCCXV$"

Tombstone_Text_Descartes::
# 1488 "data/maps/MareS1/scripts.pory"
	.string "RENATVS CARTESIVS\n"
	.string "MMCCCIL - MMCDIII$"

Tombstone_Text_Aristophanes::
# 1492 "data/maps/MareS1/scripts.pory"
	.string "ARISTOPHANES ATHENARVM\n"
	.string "CCCIX - CCCLXIX$"

Tombstone_Text_Hemingway::
# 1496 "data/maps/MareS1/scripts.pory"
	.string "ERNESTVS HEMINGWAY\n"
	.string "MMDCLII - MMDCCXIV$"

Tombstone_Text_Ginsberg::
# 1500 "data/maps/MareS1/scripts.pory"
	.string "IRVIN GINSBERG\n"
	.string "MMDCLXXIX - MMDCCL$"

Tombstone_Text_VonNeumann::
# 1504 "data/maps/MareS1/scripts.pory"
	.string "IOANNES VON NEVMANN\n"
	.string "MMDCLVI - MMDCCX$"

Tombstone_Text_Edison::
# 1508 "data/maps/MareS1/scripts.pory"
	.string "THOMAS EDISON\n"
	.string "MMDC - MMDCLXXXIV$"

Tombstone_Text_Vanderbilt::
# 1512 "data/maps/MareS1/scripts.pory"
	.string "CORNELIVS VANDERBILT\n"
	.string "MMDXLVII - MMDCCXV$"

Tombstone_Text_Leonidas::
# 1516 "data/maps/MareS1/scripts.pory"
	.string "LEONIDAS AGIADES\n"
	.string "CCXIV - CCLXXIV$"

Tombstone_Text_Pompey::
# 1520 "data/maps/MareS1/scripts.pory"
	.string "GNAEVS POMPEIVS\n"
	.string "DCXLVIII - DCCVI$"

Tombstone_Text_Pericles::
# 1524 "data/maps/MareS1/scripts.pory"
	.string "PERICLES ATHENARVM\n"
	.string "CCLIX - CCCXXV$"

Tombstone_Text_Antigonos::
# 1528 "data/maps/MareS1/scripts.pory"
	.string "ANTIGONVS MONOPHTHALMVS\n"
	.string "CCCLXXII - CDLIII$"

Tombstone_Text_Darius::
# 1532 "data/maps/MareS1/scripts.pory"
	.string "DARIVS ACHAEMENIDAE\n"
	.string "CCV - CCLXVIII$"

Tombstone_Text_Spartacus::
# 1536 "data/maps/MareS1/scripts.pory"
	.string "SPARTACVS THRACIAE\n"
	.string "DCLI - DCLXXXIII$"

Tombstone_Text_Otto::
# 1540 "data/maps/MareS1/scripts.pory"
	.string "OTTO LIVDOLFICVS\n"
	.string "MDCLXV - MDCCXXVI$"

Tombstone_Text_Justinian::
# 1544 "data/maps/MareS1/scripts.pory"
	.string "FLAVIVS PETRVS SABBATIVS IVSTINIANVS\n"
	.string "MCCXXXV - MCCCXVIII$"

Tombstone_Text_Pepin::
# 1548 "data/maps/MareS1/scripts.pory"
	.string "PIPINVS CAROLINGVS\n"
	.string "MCDLXVII - MDXXI$"

Tombstone_Text_Timur::
# 1552 "data/maps/MareS1/scripts.pory"
	.string "TAMERLANES TIMVRIDARVM\n"
	.string "MMLXXXIX- MMCLVIII$"

Tombstone_Text_Churchill::
# 1556 "data/maps/MareS1/scripts.pory"
	.string "WINSTON CHVRCHILLVS\n"
	.string "MMDCXXVII - MMDCCXVIII$"

Tombstone_Text_Henry6::
# 1560 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS VI LANCASTRIA\n"
	.string "MMCLXXIV - MMCCXXIV$"

Tombstone_Text_Hindenburg::
# 1564 "data/maps/MareS1/scripts.pory"
	.string "PAVLVS HINDENBVRG\n"
	.string "MMDC - MMDCLXXXVII$"

Tombstone_Text_Elizabeth2::
# 1568 "data/maps/MareS1/scripts.pory"
	.string "ELIZABETHA II WINDSORANI\n"
	.string "MMDCLXXIX - MMDCCLXXV$"

Tombstone_Text_Cromwell::
# 1572 "data/maps/MareS1/scripts.pory"
	.string "OLIVERIVS CROMVELLVS\n"
	.string "MMCCCLII - MMCDXI$"

Tombstone_Text_Mao::
# 1576 "data/maps/MareS1/scripts.pory"
	.string "MAO TSE TVNG\n"
	.string "MMDCXLVI - MMDCCXXIX$"

Tombstone_Text_Eisenhower::
# 1580 "data/maps/MareS1/scripts.pory"
	.string "DVIGHT EISENHOVER\n"
	.string "MMDCXLIII - MMDCCXXII$"

Tombstone_Text_Ashoka::
# 1584 "data/maps/MareS1/scripts.pory"
	.string "PIODASSES MAVRYA\n"
	.string "CDL - DXXII$"

Tombstone_Text_QinShiHuang::
# 1588 "data/maps/MareS1/scripts.pory"
	.string "CHINGVS CHI\n"
	.string "CDXCV - DXLIV$"

Tombstone_Text_Che::
# 1592 "data/maps/MareS1/scripts.pory"
	.string "ERNESTVS GVEVARA\n"
	.string "MMDCLXXXI - MMDCCXX$"

Tombstone_Text_Cincinnatus::
# 1596 "data/maps/MareS1/scripts.pory"
	.string "LVCIVS QVINCTIVS CINCINNATVS\n"
	.string "CCXXXV - CCCXXIV$"

Tombstone_Text_MarcusAurelius::
# 1600 "data/maps/MareS1/scripts.pory"
	.string "MARCVS CATILIVS SEVERVS ANNIVS VERVS\n"
	.string "DCCCLXXIV - CMXXXIII$"

Tombstone_Text_Trajan::
# 1604 "data/maps/MareS1/scripts.pory"
	.string "MARCVS VLPIVS TRAIANVS\n"
	.string "DCCCVI - DCCCLXX$"

Tombstone_Text_Urban2::
# 1608 "data/maps/MareS1/scripts.pory"
	.string "OTTO CAMPANIAE\n"
	.string "MDCCLXXXVIII - MDCCCLII$"

Tombstone_Text_Henry8::
# 1612 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS VIII TVDOR\n"
	.string "MMCCXLIV - MMCCC$"

Tombstone_Text_GustavusAdolphus::
# 1616 "data/maps/MareS1/scripts.pory"
	.string "GVSTAVS II ADOLPHVS\n"
	.string "MMCCCXLVII - MMCCCLXXXV$"

Tombstone_Text_Robespierre::
# 1620 "data/maps/MareS1/scripts.pory"
	.string "MAXIMILIANVS ROBESPIERRE\n"
	.string "MMDXI - MMDXLVII$"

Tombstone_Text_Lenin::
# 1624 "data/maps/MareS1/scripts.pory"
	.string "VLADIMIRVS LENIN\n"
	.string "MMDCXXIII - MMDCLXXVII$"

Tombstone_Text_Mandela::
# 1628 "data/maps/MareS1/scripts.pory"
	.string "NELSON MANDELA\n"
	.string "MMDCLXXI - MMDCCLXVI$"

Tombstone_Text_Catherine::
# 1632 "data/maps/MareS1/scripts.pory"
	.string "CATHARINA II ALEXII\n"
	.string "MMCDLXXXII - MMDXLIX$"

Tombstone_Text_Bolivar::
# 1636 "data/maps/MareS1/scripts.pory"
	.string "SIMON BOLIVARVS\n"
	.string "MMDXXXVI - MMDLXXXIII$"

Tombstone_Text_Bismark::
# 1640 "data/maps/MareS1/scripts.pory"
	.string "OTHO BISMARK\n"
	.string "MMDLXVIII - MMDCLI$"

Tombstone_Text_Castro::
# 1644 "data/maps/MareS1/scripts.pory"
	.string "FIDELIS CASTRO\n"
	.string "MMDCLXXIX - MMDCCLXIX$"

Tombstone_Text_FrederickGreat::
# 1648 "data/maps/MareS1/scripts.pory"
	.string "FRIDERICVS II BORVSSIAE\n"
	.string "MMCDLXV - MMDXXXIX$"

Tombstone_Text_Victoria::
# 1652 "data/maps/MareS1/scripts.pory"
	.string "ALEXANDRINA VICTORIA\n"
	.string "MMDLXXII - MMDCLIV$"

Tombstone_Text_Louis16::
# 1656 "data/maps/MareS1/scripts.pory"
	.string "LVDOVICVS XVI BORBONIENSIS\n"
	.string "MMDVII - MMDXLVI$"

Tombstone_Text_Patton::
# 1660 "data/maps/MareS1/scripts.pory"
	.string "GEORGIVS PATTON\n"
	.string "MMDCXXXVIII - MMDCXCVIII$"

Tombstone_Text_Louis14::
# 1664 "data/maps/MareS1/scripts.pory"
	.string "LVDOVICVS XIV BORBONIENSIS\n"
	.string "MMCCCXCI - MMCDLXVIII$"

Tombstone_Text_Atilla::
# 1668 "data/maps/MareS1/scripts.pory"
	.string "ATILLA HVNNORVM\n"
	.string "MCLIX - MCCVI$"

Tombstone_Text_Sulla::
# 1672 "data/maps/MareS1/scripts.pory"
	.string "LVCIVS CORNELIVS SVLLA\n"
	.string "DCXVI - DCLXXVI$"

Tombstone_Text_Xerxes::
# 1676 "data/maps/MareS1/scripts.pory"
	.string "XERXES ACHAEMENIDAE\n"
	.string "CCXXXV - CCLXXXIX$"

Tombstone_Text_Nero::
# 1680 "data/maps/MareS1/scripts.pory"
	.string "LVCIVS DOMITIVS AHENOBARBVS\n"
	.string "DCCXC - DCCCXXI$"

Tombstone_Text_EdwardPrince::
# 1684 "data/maps/MareS1/scripts.pory"
	.string "EDVARDVS WOODSTOCK ANIOV\n"
	.string "MMLXXXIII - MMCXXIX$"

Tombstone_Text_Mussolini::
# 1688 "data/maps/MareS1/scripts.pory"
	.string "BENITVS MVSSOLINI\n"
	.string "MMDCXXXVI- MMDCXCVI$"

Tombstone_Text_Gorbachev::
# 1692 "data/maps/MareS1/scripts.pory"
	.string "MICHAEL GORBACEV\n"
	.string "MMDCLXXXIV - MMDCCLXXV$"

Tombstone_Text_SusanAnthony::
# 1696 "data/maps/MareS1/scripts.pory"
	.string "SVSANA ANTONIA\n"
	.string "MMDLXXIII - MMDCLIX$"

Tombstone_Text_Henry4::
# 1700 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS IV LANCASTRIA\n"
	.string "MMCXX- MMCLXVI$"

Tombstone_Text_Franklin::
# 1704 "data/maps/MareS1/scripts.pory"
	.string "BENIAMINVS FRANKLINIVS\n"
	.string "MMCDLIX - MMDXLIII$"

Tombstone_Text_Tiberius::
# 1708 "data/maps/MareS1/scripts.pory"
	.string "TIBERIVS CLAVDIVS NERO\n"
	.string "DCCXII - DCCXC$"

Tombstone_Text_DaVinci::
# 1712 "data/maps/MareS1/scripts.pory"
	.string "LEONARDVS VINCIVS\n"
	.string "MMCCV - MMCCLXXII$"

Tombstone_Text_Pythagoras::
# 1716 "data/maps/MareS1/scripts.pory"
	.string "PYTHAGORAS SAMI\n"
	.string "CLXXXIV - CCLIX$"

Tombstone_Text_Feynman::
# 1720 "data/maps/MareS1/scripts.pory"
	.string "RICARDVS FEYNMAN\n"
	.string "MMDCLXXI - MMDCCXLI$"

Tombstone_Text_Sartre::
# 1724 "data/maps/MareS1/scripts.pory"
	.string "IOANNES SARTRE\n"
	.string "MMDCLVIII - MMDCCXXXIII$"

Tombstone_Text_Nietzshe::
# 1728 "data/maps/MareS1/scripts.pory"
	.string "FRIDERICVS NIETZSCHE\n"
	.string "MMDXCVII - MMDCLIII$"

Tombstone_Text_Joyce::
# 1732 "data/maps/MareS1/scripts.pory"
	.string "IACOBVS IOYCE\n"
	.string "MMDCXXXV - MMDCXCIV$"

Tombstone_Text_Bradly::
# 1736 "data/maps/MareS1/scripts.pory"
	.string "BRADLY NOVELL\n"
	.string "MMDCCXXI - MMDCCXLIX$"

Tombstone_Text_Constantine::
# 1740 "data/maps/MareS1/scripts.pory"
	.string "FLAVIVS VALERIVS CONSTANTINVS\n"
	.string "MXXV - MXC$"

Tombstone_Text_Henry2::
# 1744 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS II PLANTAGENISTAE\n"
	.string "MDCCCLXXXVI - MCMXLII$"

Tombstone_Text_Henry5::
# 1748 "data/maps/MareS1/scripts.pory"
	.string "HENRICVS V LANCASTRIA\n"
	.string "MMCXXXIX - MMCLXXV$"

Tombstone_Text_FrederickBarbaorossa::
# 1752 "data/maps/MareS1/scripts.pory"
	.string "FRIDERICVS I HOHENSTAVFEN\n"
	.string "MDCCCLXXV - MCMXLIII$"

Tombstone_Text_AndrewJackson::
# 1756 "data/maps/MareS1/scripts.pory"
	.string "ANDREAS IACKSON\n"
	.string "MMDXX - MMDXCVIII$"

Tombstone_Text_FDR::
# 1760 "data/maps/MareS1/scripts.pory"
	.string "FRANKLINVS ROOSEVELT\n"
	.string "MMDCXXXV - MMDCXCVIII$"

Tombstone_Text_Reagan::
# 1764 "data/maps/MareS1/scripts.pory"
	.string "RONALDVS REAGAN\n"
	.string "MMDCLXIV - MMDCCLVII$"

Tombstone_Text_Hirohito::
# 1768 "data/maps/MareS1/scripts.pory"
	.string "SHOVA HIROHITO\n"
	.string "MMDCLIV - MMDCCXLII$"

Tombstone_Text_Aquinas::
# 1772 "data/maps/MareS1/scripts.pory"
	.string "THOMAS AQUVINAS\n"
	.string "MCMLXXVIII - MMXXVII$"

Tombstone_Text_Tesla::
# 1776 "data/maps/MareS1/scripts.pory"
	.string "NICOLAVS TESLA\n"
	.string "MMDCIX - MMDCXCVI$"

Tombstone_Text_Bach::
# 1780 "data/maps/MareS1/scripts.pory"
	.string "IOANNES BACHIVS\n"
	.string "MMCDXXXVIII - MMDIII$"

Tombstone_Text_Hobbes::
# 1784 "data/maps/MareS1/scripts.pory"
	.string "THOMAS HOBBIVS\n"
	.string "MMCCCXLI - MMCDXXXII$"

Tombstone_Text_Hendrix::
# 1788 "data/maps/MareS1/scripts.pory"
	.string "IACOBVS HENDRIX\n"
	.string "MMDCXLV - MMDCCXXIII$"

Tombstone_Text_Tolkien::
# 1792 "data/maps/MareS1/scripts.pory"
	.string "IOANNES TOLKIEN\n"
	.string "MMDCXLV - MMDCCXXVI$"

Tombstone_Text_Berry::
# 1796 "data/maps/MareS1/scripts.pory"
	.string "CAROLVS BERRY\n"
	.string "MMDCLXXIX - MMDCCLXX$"

Tombstone_Text_Milton::
# 1800 "data/maps/MareS1/scripts.pory"
	.string "IOANNES MILTONVS\n"
	.string "MMCCCLXI - MMCDXXVII$"

Tombstone_Text_Sophocles::
# 1804 "data/maps/MareS1/scripts.pory"
	.string "SOPHOCLES COLONI\n"
	.string "CCLVII - CCCXLVIII$"

Tombstone_Text_Aeschylus::
# 1808 "data/maps/MareS1/scripts.pory"
	.string "AESCHYLVS ATHENARVM\n"
	.string "CCXXIX - CCXCVIII$"
