AedesAqua_WaterMaze_MapScripts::
	.byte 0


AedesAqua_WaterMaze_Script_ShowWaterStateB::
# 11 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_M_HYDRO_PUMP
# 12 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 16 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 4, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 17 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 18 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 19 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 20 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 21 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 22 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 23 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 24 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 4, METATILE_Cave_InnerCornerTopRight_Eastward, FALSE
# 26 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 5, METATILE_Cave_Right_Eastward, FALSE
# 27 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 28 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 29 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 30 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 31 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 32 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 33 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 34 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 5, METATILE_Cave_Left_Eastward, FALSE
# 36 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 6, METATILE_Cave_Right_Eastward, FALSE
# 37 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 38 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 39 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 40 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 41 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 42 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 43 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 44 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 6, METATILE_Cave_Left_Eastward, FALSE
# 46 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 7, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 47 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 7, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 48 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 49 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 50 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 51 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 52 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 53 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 54 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 55 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 7, METATILE_Cave_Left_Eastward, FALSE
# 57 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 8, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 58 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 8, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 59 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 60 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 61 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 62 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 63 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 64 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 65 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 66 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 67 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 8, METATILE_Cave_CornerBottomLeft_Eastward, FALSE
# 68 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 21, 8, METATILE_Cave_InnerCornerTopRight_Eastward, FALSE
# 70 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 9, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 71 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 72 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 73 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 74 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 75 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 76 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 77 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 78 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 79 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 80 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 81 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 21, 9, METATILE_Cave_Left_Eastward, FALSE
# 85 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 22, METATILE_Cave_CornerTopRight_Eastward, FALSE
# 86 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 22, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 87 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 22, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 88 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 22, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 89 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 22, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 90 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 22, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 92 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 23, METATILE_Cave_Right_Eastward, FALSE
# 93 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 23, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 94 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 23, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 95 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 23, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 96 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 23, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 97 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 23, METATILE_Cave_CornerTopLeft_Eastward, FALSE
# 99 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 24, METATILE_Cave_Right_Eastward, FALSE
# 100 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 24, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 101 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 24, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 102 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 24, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 103 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 24, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 104 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 24, METATILE_Cave_Left_Eastward, FALSE
# 106 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 5, 25, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 107 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 6, 25, METATILE_Cave_Bottom_Eastward, FALSE
# 108 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 7, 25, METATILE_Cave_Bottom_Eastward, FALSE
# 109 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 8, 25, METATILE_Cave_Bottom_Eastward, FALSE
# 110 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 25, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 111 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 25, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 112 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 25, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 113 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 25, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 114 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 25, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 115 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 25, METATILE_Cave_Left_Eastward, FALSE
# 117 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 5, 26, METATILE_Cave_Right_Eastward, FALSE
# 118 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 6, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 119 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 7, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 120 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 8, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 121 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 122 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 123 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 124 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 26, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 125 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 26, METATILE_Cave_CornerTopLeft_Eastward, FALSE
# 128 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	special DrawWholeMapView
# 130 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_EFFECTIVE
# 131 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
	return


AedesAqua_WaterMaze_Script_ShowWaterStateA::
# 140 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_M_HYDRO_PUMP
# 141 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 147 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 4, METATILE_Cave_InnerCornerTopLeft_Westward, FALSE
# 148 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 4, METATILE_Cave_Bottom_Westward, FALSE
# 149 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 4, METATILE_Cave_Bottom_Westward, FALSE
# 150 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 4, METATILE_Cave_Bottom_Westward, FALSE
# 151 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 4, METATILE_Cave_Bottom_Westward, FALSE
# 152 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 4, METATILE_Cave_Bottom_Westward, FALSE
# 153 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 4, METATILE_Cave_Bottom_Westward, FALSE
# 154 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 4, METATILE_Cave_Bottom_Westward, FALSE
# 155 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 4, METATILE_Cave_InnerCornerTopRight_Westward, FALSE
# 157 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 5, METATILE_Cave_Right_Westward, FALSE
# 158 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 159 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 160 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 161 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 162 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 163 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 164 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 5, METATILE_Cave_WaterCurrent_Westward, FALSE
# 165 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 5, METATILE_Cave_Left_Westward, FALSE
# 167 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 6, METATILE_Cave_Right_Westward, FALSE
# 168 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 169 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 170 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 171 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 172 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 173 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 174 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 6, METATILE_Cave_WaterCurrent_Westward, FALSE
# 175 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 6, METATILE_Cave_Left_Westward, FALSE
# 177 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 7, METATILE_Cave_InnerCornerTopLeft_Westward, FALSE
# 178 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 7, METATILE_Cave_CornerBottomRight_Westward, FALSE
# 179 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 180 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 181 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 182 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 183 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 184 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 185 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 7, METATILE_Cave_WaterCurrent_Westward, FALSE
# 186 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 7, METATILE_Cave_Left_Westward, FALSE
# 188 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 8, METATILE_Cave_InnerCornerTopLeft_Westward, FALSE
# 189 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 8, METATILE_Cave_CornerBottomRight_Westward, FALSE
# 190 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 191 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 192 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 193 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 194 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 195 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 196 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 197 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 8, METATILE_Cave_WaterCurrent_Westward, FALSE
# 198 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 8, METATILE_Cave_CornerBottomLeft_Westward, FALSE
# 199 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 21, 8, METATILE_Cave_InnerCornerTopRight_Westward, FALSE
# 201 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 9, METATILE_Cave_CornerBottomRight_Westward, FALSE
# 202 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 203 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 204 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 205 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 206 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 207 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 208 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 209 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 210 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 211 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 9, METATILE_Cave_WaterCurrent_Westward, FALSE
# 212 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 21, 9, METATILE_Cave_Left_Westward, FALSE
# 216 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 22, METATILE_Cave_CornerTopRight_Westward, FALSE
# 217 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 22, METATILE_Cave_WaterCurrent_Westward, FALSE
# 218 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 22, METATILE_Cave_WaterCurrent_Westward, FALSE
# 219 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 22, METATILE_Cave_WaterCurrent_Westward, FALSE
# 220 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 22, METATILE_Cave_WaterCurrent_Westward, FALSE
# 221 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 22, METATILE_Cave_WaterCurrent_Westward, FALSE
# 223 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 23, METATILE_Cave_Right_Westward, FALSE
# 224 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 23, METATILE_Cave_WaterCurrent_Westward, FALSE
# 225 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 23, METATILE_Cave_WaterCurrent_Westward, FALSE
# 226 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 23, METATILE_Cave_WaterCurrent_Westward, FALSE
# 227 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 23, METATILE_Cave_WaterCurrent_Westward, FALSE
# 228 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 23, METATILE_Cave_CornerTopLeft_Westward, FALSE
# 230 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 24, METATILE_Cave_Right_Westward, FALSE
# 231 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 24, METATILE_Cave_WaterCurrent_Westward, FALSE
# 232 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 24, METATILE_Cave_WaterCurrent_Westward, FALSE
# 233 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 24, METATILE_Cave_WaterCurrent_Westward, FALSE
# 234 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 24, METATILE_Cave_WaterCurrent_Westward, FALSE
# 235 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 24, METATILE_Cave_Left_Westward, FALSE
# 237 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 5, 25, METATILE_Cave_InnerCornerTopLeft_Westward, FALSE
# 238 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 6, 25, METATILE_Cave_Bottom_Westward, FALSE
# 239 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 7, 25, METATILE_Cave_Bottom_Westward, FALSE
# 240 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 8, 25, METATILE_Cave_Bottom_Westward, FALSE
# 241 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 25, METATILE_Cave_CornerBottomRight_Westward, FALSE
# 242 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 25, METATILE_Cave_WaterCurrent_Westward, FALSE
# 243 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 25, METATILE_Cave_WaterCurrent_Westward, FALSE
# 244 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 25, METATILE_Cave_WaterCurrent_Westward, FALSE
# 245 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 25, METATILE_Cave_WaterCurrent_Westward, FALSE
# 246 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 25, METATILE_Cave_Left_Westward, FALSE
# 248 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 5, 26, METATILE_Cave_Right_Westward, FALSE
# 249 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 6, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 250 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 7, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 251 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 8, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 252 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 9, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 253 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 254 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 255 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 26, METATILE_Cave_WaterCurrent_Westward, FALSE
# 256 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 26, METATILE_Cave_CornerTopLeft_Westward, FALSE
# 259 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_EFFECTIVE
# 260 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 262 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	special DrawWholeMapView
	return


AedesAqua_WaterMaze_Script_WaterSwitchR::
# 270 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	msgbox AedesAqua_Text_WaterControl, MSGBOX_YESNO
# 271 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	closemessage
# 272 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq AedesAqua_WaterMaze_Script_WaterSwitchR_3
AedesAqua_WaterMaze_Script_WaterSwitchR_1:
	end

AedesAqua_WaterMaze_Script_WaterSwitchR_2:
# 273 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setflag FLAG_TEMP_6
# 274 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	call AedesAqua_WaterMaze_Script_ShowWaterStateA
	goto AedesAqua_WaterMaze_Script_WaterSwitchR_1

AedesAqua_WaterMaze_Script_WaterSwitchR_3:
# 272 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	goto_if_unset FLAG_TEMP_6, AedesAqua_WaterMaze_Script_WaterSwitchR_2
	goto AedesAqua_WaterMaze_Script_WaterSwitchR_1


AedesAqua_WaterMaze_Script_WaterSwitchL::
# 280 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	msgbox AedesAqua_Text_WaterControl, MSGBOX_YESNO
# 281 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	closemessage
# 282 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq AedesAqua_WaterMaze_Script_WaterSwitchL_3
AedesAqua_WaterMaze_Script_WaterSwitchL_1:
	end

AedesAqua_WaterMaze_Script_WaterSwitchL_2:
# 283 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	clearflag FLAG_TEMP_6
# 284 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	call AedesAqua_WaterMaze_Script_ShowWaterStateB
	goto AedesAqua_WaterMaze_Script_WaterSwitchL_1

AedesAqua_WaterMaze_Script_WaterSwitchL_3:
# 282 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	goto_if_set FLAG_TEMP_6, AedesAqua_WaterMaze_Script_WaterSwitchL_2
	goto AedesAqua_WaterMaze_Script_WaterSwitchL_1

