AedesAqua_WaterMaze_MapScripts::
	.byte 0


AedesAqua_WaterMaze_Script_ShowWaterStateA::
# 11 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_M_HYDRO_PUMP
# 12 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 18 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 4, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 19 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 20 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 21 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 22 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 23 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 24 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 25 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 4, METATILE_Cave_Bottom_Eastward, FALSE
# 26 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 4, METATILE_Cave_InnerCornerTopRight_Eastward, FALSE
# 28 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 5, METATILE_Cave_Right_Eastward, FALSE
# 29 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 30 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 31 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 32 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 33 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 34 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 35 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 5, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 36 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 5, METATILE_Cave_Left_Eastward, FALSE
# 38 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 6, METATILE_Cave_Right_Eastward, FALSE
# 39 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 40 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 41 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 42 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 43 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 44 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 45 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 6, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 46 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 6, METATILE_Cave_Left_Eastward, FALSE
# 48 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 7, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 49 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 7, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 50 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 51 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 52 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 53 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 54 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 55 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 56 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 7, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 57 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 7, METATILE_Cave_Left_Eastward, FALSE
# 59 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 8, METATILE_Cave_InnerCornerTopLeft_Eastward, FALSE
# 60 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 8, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 61 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 62 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 63 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 64 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 65 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 66 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 67 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 68 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 8, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 69 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 8, METATILE_Cave_CornerBottomLeft_Eastward, FALSE
# 70 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 21, 8, METATILE_Cave_InnerCornerTopRight_Eastward, FALSE
# 72 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 10, 9, METATILE_Cave_CornerBottomRight_Eastward, FALSE
# 73 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 11, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 74 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 12, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 75 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 13, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 76 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 14, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 77 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 15, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 78 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 16, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 79 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 17, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 80 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 18, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 81 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 19, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 82 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 20, 9, METATILE_Cave_WaterCurrent_Eastward, FALSE
# 83 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setmetatile 21, 9, METATILE_Cave_Left_Eastward, FALSE
# 93 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_EFFECTIVE
# 94 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 96 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	special DrawWholeMapView
	return


AedesAqua_WaterMaze_Script_ShowWaterStateB::
# 104 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_M_HYDRO_PUMP
# 105 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 125 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	playse SE_EFFECTIVE
# 126 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	waitse
# 128 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	special DrawWholeMapView
	return


AedesAqua_WaterMaze_Script_WaterSwitchR::
# 136 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	msgbox AedesAqua_Text_WaterControl, MSGBOX_YESNO
# 137 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	closemessage
# 138 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq AedesAqua_WaterMaze_Script_WaterSwitchR_3
AedesAqua_WaterMaze_Script_WaterSwitchR_1:
	end

AedesAqua_WaterMaze_Script_WaterSwitchR_2:
# 139 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	clearflag FLAG_TEMP_6
# 140 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	call AedesAqua_WaterMaze_Script_ShowWaterStateA
	goto AedesAqua_WaterMaze_Script_WaterSwitchR_1

AedesAqua_WaterMaze_Script_WaterSwitchR_3:
# 138 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	goto_if_set FLAG_TEMP_6, AedesAqua_WaterMaze_Script_WaterSwitchR_2
	goto AedesAqua_WaterMaze_Script_WaterSwitchR_1


AedesAqua_WaterMaze_Script_WaterSwitchL::
# 146 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	msgbox AedesAqua_Text_WaterControl, MSGBOX_YESNO
# 147 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	closemessage
# 148 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	compare VAR_RESULT, TRUE
	goto_if_eq AedesAqua_WaterMaze_Script_WaterSwitchL_3
AedesAqua_WaterMaze_Script_WaterSwitchL_1:
	end

AedesAqua_WaterMaze_Script_WaterSwitchL_2:
# 149 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	setflag FLAG_TEMP_6
# 150 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	call AedesAqua_WaterMaze_Script_ShowWaterStateB
	goto AedesAqua_WaterMaze_Script_WaterSwitchL_1

AedesAqua_WaterMaze_Script_WaterSwitchL_3:
# 148 "data/maps/AedesAqua_WaterMaze/scripts.pory"
	goto_if_unset FLAG_TEMP_6, AedesAqua_WaterMaze_Script_WaterSwitchL_2
	goto AedesAqua_WaterMaze_Script_WaterSwitchL_1

