Warehouse_Blue_MapScripts::
	.byte 0


Warehouse_Blue_EventScript_TrainerBlue5::
# 6 "data/maps/Warehouse_Blue/scripts.pory"
	trainerbattle_single TRAINER_BLUE5, Warehouse_Blue_Text_Blue5Intro, Warehouse_Blue_Text_Blue5Lost
# 7 "data/maps/Warehouse_Blue/scripts.pory"
	msgbox Warehouse_Blue_Text_Blue5Post
# 8 "data/maps/Warehouse_Blue/scripts.pory"
	closemessage
	end


Warehouse_Blue_EventScript_TrainerBlue4::
# 12 "data/maps/Warehouse_Blue/scripts.pory"
	trainerbattle_single TRAINER_BLUE4, Warehouse_Blue_Text_Blue4Intro, Warehouse_Blue_Text_Blue4Lost
# 13 "data/maps/Warehouse_Blue/scripts.pory"
	msgbox Warehouse_Blue_Text_Blue4Post
# 14 "data/maps/Warehouse_Blue/scripts.pory"
	closemessage
	end


Warehouse_Blue_EventScript_TrainerBlue3::
# 19 "data/maps/Warehouse_Blue/scripts.pory"
	trainerbattle_single TRAINER_BLUE3, Warehouse_Blue_Text_Blue3Intro, Warehouse_Blue_Text_Blue3Lost
# 20 "data/maps/Warehouse_Blue/scripts.pory"
	msgbox Warehouse_Blue_Text_Blue3Post
# 21 "data/maps/Warehouse_Blue/scripts.pory"
	closemessage
	end


Warehouse_Blue_EventScript_TrainerBlue2::
# 26 "data/maps/Warehouse_Blue/scripts.pory"
	trainerbattle_single TRAINER_BLUE2, Warehouse_Blue_Text_Blue2Intro, Warehouse_Blue_Text_Blue2Lost
# 27 "data/maps/Warehouse_Blue/scripts.pory"
	msgbox Warehouse_Blue_Text_Blue2Post
# 28 "data/maps/Warehouse_Blue/scripts.pory"
	closemessage
	end


Warehouse_Blue_EventScript_TrainerBlue1::
# 33 "data/maps/Warehouse_Blue/scripts.pory"
	trainerbattle_single TRAINER_BLUE1, Warehouse_Blue_Text_Blue1Intro, Warehouse_Blue_Text_Blue1Lost
# 34 "data/maps/Warehouse_Blue/scripts.pory"
	msgbox Warehouse_Blue_Text_Blue1Post
# 35 "data/maps/Warehouse_Blue/scripts.pory"
	closemessage
	end


Warehouse_Blue_Text_Blue5Intro::
# 39 "data/maps/Warehouse_Blue/scripts.pory"
	.string "You're in the trenches! This the pit\n"
	.string "spot bro you already know.$"

Warehouse_Blue_Text_Blue5Lost::
# 43 "data/maps/Warehouse_Blue/scripts.pory"
	.string "But, like, we didn't come yesterday to\n"
	.string "lose.$"

Warehouse_Blue_Text_Blue5Post::
# 47 "data/maps/Warehouse_Blue/scripts.pory"
	.string "When you step out here we show love. We\n"
	.string "show mad love to everybody you\l"
	.string "understand?$"

Warehouse_Blue_Text_Blue4Intro::
# 51 "data/maps/Warehouse_Blue/scripts.pory"
	.string "I'm blessed! This my third fight in three\n"
	.string "years.$"

Warehouse_Blue_Text_Blue4Lost::
# 55 "data/maps/Warehouse_Blue/scripts.pory"
	.string "That's what happened. I'm keep my faith\n"
	.string "in God.$"

Warehouse_Blue_Text_Blue4Post::
# 59 "data/maps/Warehouse_Blue/scripts.pory"
	.string "Everyone else going crazy I'm more chill\n"
	.string "about those things man.$"

Warehouse_Blue_Text_Blue3Intro::
# 63 "data/maps/Warehouse_Blue/scripts.pory"
	.string "I'm very happy the public enjoys what I\n"
	.string "do.$"

Warehouse_Blue_Text_Blue3Lost::
# 67 "data/maps/Warehouse_Blue/scripts.pory"
	.string "I will continue to put a lot of pride in\n"
	.string "my work.$"

Warehouse_Blue_Text_Blue3Post::
# 71 "data/maps/Warehouse_Blue/scripts.pory"
	.string "Every time I take an L I never take it\n"
	.string "lightly.$"

Warehouse_Blue_Text_Blue2Intro::
# 75 "data/maps/Warehouse_Blue/scripts.pory"
	.string "Time to prove it again. Every time you\n"
	.string "step in the ring you gotta prove it.$"

Warehouse_Blue_Text_Blue2Lost::
# 79 "data/maps/Warehouse_Blue/scripts.pory"
	.string "They should do a lightweight\n"
	.string "tournement.$"

Warehouse_Blue_Text_Blue2Post::
# 83 "data/maps/Warehouse_Blue/scripts.pory"
	.string "Ahh you destroyed everybody!$"

Warehouse_Blue_Text_Blue1Intro::
# 87 "data/maps/Warehouse_Blue/scripts.pory"
	.string "We world champions! This our street!$"

Warehouse_Blue_Text_Blue1Lost::
# 91 "data/maps/Warehouse_Blue/scripts.pory"
	.string "We gonna do it again for the Blue tho.$"

Warehouse_Blue_Text_Blue1Post::
# 95 "data/maps/Warehouse_Blue/scripts.pory"
	.string "Dang we was flat. Just kind of let you\n"
	.string "go where you wanted to go. Damn.$"
