Argo_MapScripts::
	.byte 0


Argo_EventScript_ExitWarp::
# 8 "data/maps/Argo/scripts.pory"
	lock
# 9 "data/maps/Argo/scripts.pory"
	warpsilent MAP_MARE_S5, 45, 43
# 10 "data/maps/Argo/scripts.pory"
	waitstate
# 11 "data/maps/Argo/scripts.pory"
	release
	end


Argo_Script_Castor::
	end


Argo_Script_Pollux::
	end


Argo_Script_Theseus::
	end


Argo_Script_Orpheus::
	end


Argo_Script_Philoctetes::
# 36 "data/maps/Argo/scripts.pory"
	lock
# 37 "data/maps/Argo/scripts.pory"
	faceplayer
# 40 "data/maps/Argo/scripts.pory"
	release
	end


Argo_Script_Jason::
# 45 "data/maps/Argo/scripts.pory"
	lock
# 46 "data/maps/Argo/scripts.pory"
	faceplayer
# 49 "data/maps/Argo/scripts.pory"
	release
	end

